#!/usr/bin/env python3
"""
Genera data/sft_mini.jsonl — dataset SFT per intent recognition in italiano.
140 coppie prompt/completion su 6 intent:
  create_event, reschedule_event, delete_event,
  create_reminder, query_schedule, add_contact
"""

import json
from pathlib import Path

pairs = []

# ─────────────────────────────────────────────────────────────────────────────
# CREATE EVENT (25)
# ─────────────────────────────────────────────────────────────────────────────
pairs += [
    ("Crea un appuntamento con Marco venerdì alle 15.",
     {"intent": "create_event", "contact": "Marco", "date": "venerdì", "time": "15:00"}),
    ("Segna una riunione con il team domani mattina alle 9.",
     {"intent": "create_event", "title": "riunione team", "contact": "team", "date": "domani", "time": "09:00"}),
    ("Ho bisogno di fissare un meeting con Sara e Luca mercoledì pomeriggio.",
     {"intent": "create_event", "title": "meeting", "contact": ["Sara", "Luca"], "date": "mercoledì", "time": "pomeriggio"}),
    ("Metti in agenda una call con il cliente alle 14:30 di giovedì.",
     {"intent": "create_event", "title": "call cliente", "date": "giovedì", "time": "14:30"}),
    ("Aggiungi un appuntamento dal medico lunedì alle 10.",
     {"intent": "create_event", "title": "medico", "date": "lunedì", "time": "10:00"}),
    ("Crea un evento per la presentazione del progetto il 20 ottobre alle 11.",
     {"intent": "create_event", "title": "presentazione progetto", "date": "20 ottobre", "time": "11:00"}),
    ("Organizza una cena con i colleghi venerdì sera.",
     {"intent": "create_event", "title": "cena colleghi", "contact": "colleghi", "date": "venerdì", "time": "sera"}),
    ("Prenota una sala riunioni per domani dalle 14 alle 16.",
     {"intent": "create_event", "title": "sala riunioni", "date": "domani", "time": "14:00", "duration": "2 ore"}),
    ("Fissa una videochiamata con il responsabile tecnico martedì alle 9:30.",
     {"intent": "create_event", "title": "videochiamata", "contact": "responsabile tecnico", "date": "martedì", "time": "09:30"}),
    ("Metti in calendario la revisione del budget per la settimana prossima, preferibilmente di mattina.",
     {"intent": "create_event", "title": "revisione budget", "date": "settimana prossima", "time": "mattina"}),
    ("Crea un appuntamento con il dentista il prossimo venerdì alle 16.",
     {"intent": "create_event", "title": "dentista", "date": "prossimo venerdì", "time": "16:00"}),
    ("Aggiungi in agenda: colloquio con il candidato Andrea Rossi giovedì alle 10.",
     {"intent": "create_event", "title": "colloquio", "contact": "Andrea Rossi", "date": "giovedì", "time": "10:00"}),
    ("Ho una riunione di dipartimento ogni martedì alle 11, aggiungila.",
     {"intent": "create_event", "title": "riunione dipartimento", "date": "ogni martedì", "time": "11:00", "recurrence": "settimanale"}),
    ("Crea un evento per il pranzo con Giulia domani all'una.",
     {"intent": "create_event", "title": "pranzo", "contact": "Giulia", "date": "domani", "time": "13:00"}),
    ("Fissa l'appuntamento con il notaio per il 3 novembre alle 15:30.",
     {"intent": "create_event", "title": "notaio", "date": "3 novembre", "time": "15:30"}),
    ("Aggiungi in agenda la call settimanale di allineamento il lunedì alle 9.",
     {"intent": "create_event", "title": "call allineamento", "date": "lunedì", "time": "09:00", "recurrence": "settimanale"}),
    ("Crea un evento: review del codice con Kevin e Mattia mercoledì alle 14.",
     {"intent": "create_event", "title": "review codice", "contact": ["Kevin", "Mattia"], "date": "mercoledì", "time": "14:00"}),
    ("Segna la scadenza fiscale per il 31 ottobre.",
     {"intent": "create_event", "title": "scadenza fiscale", "date": "31 ottobre"}),
    ("Organizza una sessione di brainstorming venerdì mattina per due ore.",
     {"intent": "create_event", "title": "brainstorming", "date": "venerdì", "time": "mattina", "duration": "2 ore"}),
    ("Metti in calendario: appello universitario il 15 novembre alle 9.",
     {"intent": "create_event", "title": "appello universitario", "date": "15 novembre", "time": "09:00"}),
    ("Crea una riunione con il fornitore la prossima settimana, martedì o mercoledì.",
     {"intent": "create_event", "title": "riunione fornitore", "date": "prossima settimana", "time_preference": "martedì o mercoledì"}),
    ("Aggiungi un appuntamento: consulenza con l'avvocato giovedì pomeriggio.",
     {"intent": "create_event", "title": "consulenza avvocato", "date": "giovedì", "time": "pomeriggio"}),
    ("Fissa una call di onboarding con il nuovo collega lunedì mattina.",
     {"intent": "create_event", "title": "call onboarding", "date": "lunedì", "time": "mattina"}),
    ("Ho un appuntamento in banca domani alle 11:15, mettilo in agenda.",
     {"intent": "create_event", "title": "banca", "date": "domani", "time": "11:15"}),
    ("Crea un evento per il webinar sul machine learning il 22 ottobre dalle 15 alle 17.",
     {"intent": "create_event", "title": "webinar machine learning", "date": "22 ottobre", "time": "15:00", "duration": "2 ore"}),
]

# ─────────────────────────────────────────────────────────────────────────────
# RESCHEDULE EVENT (25)
# ─────────────────────────────────────────────────────────────────────────────
pairs += [
    ("Sposta la riunione con Marco a giovedì pomeriggio.",
     {"intent": "reschedule_event", "contact": "Marco", "new_date": "giovedì", "new_time": "pomeriggio"}),
    ("Devo posticipare il meeting di domani mattina a venerdì alle 10.",
     {"intent": "reschedule_event", "event_ref": "meeting domani mattina", "new_date": "venerdì", "new_time": "10:00"}),
    ("La riunione con Sara è stata anticipata a martedì alle 14.",
     {"intent": "reschedule_event", "contact": "Sara", "new_date": "martedì", "new_time": "14:00"}),
    ("Sposta la call con il cliente di giovedì a lunedì alle 9.",
     {"intent": "reschedule_event", "event_ref": "call cliente giovedì", "new_date": "lunedì", "new_time": "09:00"}),
    ("Il colloquio di domani va spostato alla settimana prossima.",
     {"intent": "reschedule_event", "event_ref": "colloquio domani", "new_date": "settimana prossima"}),
    ("Posticipa l'appuntamento dal medico di venerdì a martedì 28.",
     {"intent": "reschedule_event", "event_ref": "appuntamento medico venerdì", "new_date": "martedì 28"}),
    ("Dobbiamo spostare la riunione di team di mercoledì, possiamo fare giovedì alla stessa ora?",
     {"intent": "reschedule_event", "event_ref": "riunione team mercoledì", "new_date": "giovedì"}),
    ("La presentazione del progetto è slittata al 25 ottobre alle 11.",
     {"intent": "reschedule_event", "event_ref": "presentazione progetto", "new_date": "25 ottobre", "new_time": "11:00"}),
    ("Aggiorna il meeting con Luca: non più lunedì ma mercoledì alle 15.",
     {"intent": "reschedule_event", "contact": "Luca", "new_date": "mercoledì", "new_time": "15:00"}),
    ("Ho bisogno di spostare la call delle 14 di oggi a domani alla stessa ora.",
     {"intent": "reschedule_event", "event_ref": "call 14:00 oggi", "new_date": "domani", "new_time": "14:00"}),
    ("Sposta il pranzo con il team da venerdì a giovedì.",
     {"intent": "reschedule_event", "event_ref": "pranzo team venerdì", "new_date": "giovedì"}),
    ("La videochiamata con il responsabile commerciale va anticipata a questa mattina.",
     {"intent": "reschedule_event", "event_ref": "videochiamata responsabile commerciale", "new_date": "oggi", "new_time": "mattina"}),
    ("Aggiorna il calendario: la scadenza del 31 è posticipata al 5 novembre.",
     {"intent": "reschedule_event", "event_ref": "scadenza 31", "new_date": "5 novembre"}),
    ("Devo rimandare il colloquio con Andrea Rossi, può fare la prossima settimana?",
     {"intent": "reschedule_event", "contact": "Andrea Rossi", "event_ref": "colloquio", "new_date": "prossima settimana"}),
    ("Sposta la riunione delle 9 di domani mattina alle 11.",
     {"intent": "reschedule_event", "event_ref": "riunione 09:00 domani", "new_date": "domani", "new_time": "11:00"}),
    ("Il meeting di allineamento di lunedì è stato cancellato e spostato a mercoledì alle 9.",
     {"intent": "reschedule_event", "event_ref": "meeting allineamento lunedì", "new_date": "mercoledì", "new_time": "09:00"}),
    ("Rinvia l'appuntamento con il notaio di una settimana.",
     {"intent": "reschedule_event", "event_ref": "appuntamento notaio", "new_date": "una settimana dopo"}),
    ("Aggiorna: il webinar del 22 è spostato al 29 ottobre, stessa ora.",
     {"intent": "reschedule_event", "event_ref": "webinar 22 ottobre", "new_date": "29 ottobre"}),
    ("Devo spostare la revisione del budget: non più martedì prossimo ma giovedì.",
     {"intent": "reschedule_event", "event_ref": "revisione budget martedì prossimo", "new_date": "giovedì"}),
    ("La consulenza con l'avvocato è stata spostata alle 16 dello stesso giorno.",
     {"intent": "reschedule_event", "event_ref": "consulenza avvocato", "new_time": "16:00"}),
    ("Posticipa tutte le riunioni di domani al giorno dopo.",
     {"intent": "reschedule_event", "event_ref": "riunioni domani", "new_date": "dopodomani", "scope": "all"}),
    ("Sposta il meeting con Kevin e Mattia a venerdì mattina.",
     {"intent": "reschedule_event", "contact": ["Kevin", "Mattia"], "new_date": "venerdì", "new_time": "mattina"}),
    ("L'appello del 15 novembre è anticipato al 12 novembre alla stessa ora.",
     {"intent": "reschedule_event", "event_ref": "appello 15 novembre", "new_date": "12 novembre"}),
    ("Ho dovuto spostare il pranzo con Giulia: ora è sabato a mezzogiorno.",
     {"intent": "reschedule_event", "contact": "Giulia", "event_ref": "pranzo Giulia", "new_date": "sabato", "new_time": "12:00"}),
    ("Aggiorna la call di onboarding: non lunedì mattina ma martedì alle 10.",
     {"intent": "reschedule_event", "event_ref": "call onboarding lunedì", "new_date": "martedì", "new_time": "10:00"}),
]

# ─────────────────────────────────────────────────────────────────────────────
# DELETE EVENT (20)
# ─────────────────────────────────────────────────────────────────────────────
pairs += [
    ("Cancella l'appuntamento con Marco di venerdì.",
     {"intent": "delete_event", "contact": "Marco", "date": "venerdì"}),
    ("Rimuovi il meeting di domani mattina dal calendario.",
     {"intent": "delete_event", "event_ref": "meeting domani mattina"}),
    ("Elimina tutti gli appuntamenti di lunedì.",
     {"intent": "delete_event", "date": "lunedì", "scope": "all"}),
    ("Cancella la riunione con Sara di martedì alle 14.",
     {"intent": "delete_event", "contact": "Sara", "date": "martedì", "time": "14:00"}),
    ("Togli dal calendario la call con il cliente di giovedì.",
     {"intent": "delete_event", "event_ref": "call cliente", "date": "giovedì"}),
    ("Elimina il pranzo con i colleghi di venerdì.",
     {"intent": "delete_event", "event_ref": "pranzo colleghi", "date": "venerdì"}),
    ("Cancella l'appuntamento dal dentista.",
     {"intent": "delete_event", "event_ref": "appuntamento dentista"}),
    ("Rimuovi tutti gli eventi della prossima settimana.",
     {"intent": "delete_event", "date": "prossima settimana", "scope": "all"}),
    ("Elimina la riunione di allineamento del lunedì.",
     {"intent": "delete_event", "event_ref": "riunione allineamento lunedì"}),
    ("Cancella il webinar del 22 ottobre.",
     {"intent": "delete_event", "event_ref": "webinar", "date": "22 ottobre"}),
    ("Togli la revisione del budget dall'agenda.",
     {"intent": "delete_event", "event_ref": "revisione budget"}),
    ("Elimina il colloquio con Andrea Rossi.",
     {"intent": "delete_event", "event_ref": "colloquio", "contact": "Andrea Rossi"}),
    ("Rimuovi l'appuntamento in banca di domani alle 11:15.",
     {"intent": "delete_event", "event_ref": "banca", "date": "domani", "time": "11:15"}),
    ("Cancella tutti i meeting con il fornitore questa settimana.",
     {"intent": "delete_event", "contact": "fornitore", "date": "questa settimana", "scope": "all"}),
    ("Elimina la videochiamata di martedì mattina.",
     {"intent": "delete_event", "event_ref": "videochiamata", "date": "martedì", "time": "mattina"}),
    ("Rimuovi la cena con i colleghi di venerdì sera.",
     {"intent": "delete_event", "event_ref": "cena colleghi", "date": "venerdì", "time": "sera"}),
    ("Cancella l'evento del 3 novembre con il notaio.",
     {"intent": "delete_event", "event_ref": "notaio", "date": "3 novembre"}),
    ("Elimina le riunioni ricorrenti del martedì mattina.",
     {"intent": "delete_event", "event_ref": "riunioni ricorrenti martedì", "recurrence": "settimanale"}),
    ("Togli dal calendario la sessione di brainstorming di venerdì.",
     {"intent": "delete_event", "event_ref": "brainstorming", "date": "venerdì"}),
    ("Cancella tutto quello che ho giovedì pomeriggio.",
     {"intent": "delete_event", "date": "giovedì", "time": "pomeriggio", "scope": "all"}),
]

# ─────────────────────────────────────────────────────────────────────────────
# CREATE REMINDER (25)
# ─────────────────────────────────────────────────────────────────────────────
pairs += [
    ("Aggiungi un promemoria per domani mattina: chiamare il medico.",
     {"intent": "create_reminder", "note": "chiamare il medico", "date": "domani", "time": "mattina"}),
    ("Ricordami di mandare la fattura a fine mese.",
     {"intent": "create_reminder", "note": "mandare la fattura", "date": "fine mese"}),
    ("Metti un reminder per venerdì alle 17: inviare il report settimanale.",
     {"intent": "create_reminder", "note": "inviare il report settimanale", "date": "venerdì", "time": "17:00"}),
    ("Ricordami di comprare un regalo per il compleanno di Giulia, il 15.",
     {"intent": "create_reminder", "note": "comprare regalo compleanno Giulia", "date": "15"}),
    ("Aggiungi promemoria: pagare la bolletta entro il 20.",
     {"intent": "create_reminder", "note": "pagare la bolletta", "deadline": "20"}),
    ("Ricordami domani alle 8 di portare i documenti in ufficio.",
     {"intent": "create_reminder", "note": "portare i documenti in ufficio", "date": "domani", "time": "08:00"}),
    ("Metti un reminder per lunedì prossimo: rinnovare l'abbonamento.",
     {"intent": "create_reminder", "note": "rinnovare l'abbonamento", "date": "lunedì prossimo"}),
    ("Ricordami di rispondere alla mail di Marco entro oggi.",
     {"intent": "create_reminder", "note": "rispondere alla mail di Marco", "deadline": "oggi"}),
    ("Aggiungi un promemoria per le 9 di domani: call con il fornitore.",
     {"intent": "create_reminder", "note": "call con il fornitore", "date": "domani", "time": "09:00"}),
    ("Ricordami di prenotare il volo per il 5 novembre.",
     {"intent": "create_reminder", "note": "prenotare il volo", "deadline": "5 novembre"}),
    ("Metti un avviso per giovedì: scade la garanzia del laptop.",
     {"intent": "create_reminder", "note": "scade la garanzia del laptop", "date": "giovedì"}),
    ("Ricordami di aggiornare il CV prima di venerdì.",
     {"intent": "create_reminder", "note": "aggiornare il CV", "deadline": "venerdì"}),
    ("Aggiungi promemoria: ritirare il pacco in ufficio postale domani.",
     {"intent": "create_reminder", "note": "ritirare il pacco in ufficio postale", "date": "domani"}),
    ("Ricordami ogni lunedì mattina di fare il backup del server.",
     {"intent": "create_reminder", "note": "fare il backup del server", "date": "ogni lunedì", "time": "mattina", "recurrence": "settimanale"}),
    ("Metti un reminder per il 31 ottobre: scadenza dichiarazione fiscale.",
     {"intent": "create_reminder", "note": "scadenza dichiarazione fiscale", "date": "31 ottobre"}),
    ("Ricordami di chiamare il commercialista la prossima settimana.",
     {"intent": "create_reminder", "note": "chiamare il commercialista", "date": "prossima settimana"}),
    ("Aggiungi avviso: confermare partecipazione al convegno entro mercoledì.",
     {"intent": "create_reminder", "note": "confermare partecipazione al convegno", "deadline": "mercoledì"}),
    ("Ricordami di mandare il contratto firmato a Sara entro domani.",
     {"intent": "create_reminder", "note": "mandare contratto firmato a Sara", "deadline": "domani"}),
    ("Metti un promemoria per questa sera alle 20: telefonare a casa.",
     {"intent": "create_reminder", "note": "telefonare a casa", "date": "oggi", "time": "20:00"}),
    ("Ricordami di fare la spesa sabato mattina.",
     {"intent": "create_reminder", "note": "fare la spesa", "date": "sabato", "time": "mattina"}),
    ("Aggiungi un reminder: revisione trimestrale il primo lunedì di novembre.",
     {"intent": "create_reminder", "note": "revisione trimestrale", "date": "primo lunedì di novembre"}),
    ("Ricordami di leggere il verbale della riunione di oggi entro stasera.",
     {"intent": "create_reminder", "note": "leggere il verbale della riunione", "date": "oggi", "time": "stasera"}),
    ("Metti un avviso domani alle 7:30: preparare la presentazione.",
     {"intent": "create_reminder", "note": "preparare la presentazione", "date": "domani", "time": "07:30"}),
    ("Ricordami di ringraziare Luca per l'aiuto di questa settimana.",
     {"intent": "create_reminder", "note": "ringraziare Luca", "date": "presto"}),
    ("Aggiungi promemoria per mercoledì: verificare lo stato del progetto con il team.",
     {"intent": "create_reminder", "note": "verificare stato del progetto con il team", "date": "mercoledì"}),
]

# ─────────────────────────────────────────────────────────────────────────────
# QUERY SCHEDULE (25)
# ─────────────────────────────────────────────────────────────────────────────
pairs += [
    ("Cosa ho in agenda domani?",
     {"intent": "query_schedule", "date": "domani"}),
    ("Quali appuntamenti ho questa settimana?",
     {"intent": "query_schedule", "date": "questa settimana"}),
    ("Ho qualcosa con Marco venerdì?",
     {"intent": "query_schedule", "contact": "Marco", "date": "venerdì"}),
    ("Mostrami tutti gli eventi di lunedì prossimo.",
     {"intent": "query_schedule", "date": "lunedì prossimo"}),
    ("Sono libero domani pomeriggio?",
     {"intent": "query_schedule", "date": "domani", "time": "pomeriggio", "query_type": "availability"}),
    ("A che ora è la riunione con Sara?",
     {"intent": "query_schedule", "contact": "Sara", "query_type": "time_of_event"}),
    ("Cosa ho nel calendario il 20 ottobre?",
     {"intent": "query_schedule", "date": "20 ottobre"}),
    ("Quante riunioni ho questa settimana?",
     {"intent": "query_schedule", "date": "questa settimana", "query_type": "count"}),
    ("Ho impegni martedì mattina?",
     {"intent": "query_schedule", "date": "martedì", "time": "mattina", "query_type": "availability"}),
    ("Mostrami i prossimi appuntamenti con il cliente.",
     {"intent": "query_schedule", "contact": "cliente", "query_type": "upcoming"}),
    ("Qual è il mio primo impegno di domani?",
     {"intent": "query_schedule", "date": "domani", "query_type": "first_event"}),
    ("Cosa ho tra le 14 e le 17 di giovedì?",
     {"intent": "query_schedule", "date": "giovedì", "time_range": "14:00-17:00"}),
    ("Ci sono riunioni in programma con Kevin questa settimana?",
     {"intent": "query_schedule", "contact": "Kevin", "date": "questa settimana"}),
    ("Quando è il prossimo appuntamento dal medico?",
     {"intent": "query_schedule", "event_ref": "medico", "query_type": "next_occurrence"}),
    ("Ho slot liberi venerdì mattina per aggiungere una call?",
     {"intent": "query_schedule", "date": "venerdì", "time": "mattina", "query_type": "availability"}),
    ("Cosa ho in agenda la settimana prossima nel pomeriggio?",
     {"intent": "query_schedule", "date": "prossima settimana", "time": "pomeriggio"}),
    ("Ci sono conflitti martedì alle 10?",
     {"intent": "query_schedule", "date": "martedì", "time": "10:00", "query_type": "conflicts"}),
    ("Mostrami tutti gli appuntamenti con il notaio.",
     {"intent": "query_schedule", "contact": "notaio", "query_type": "all"}),
    ("Quando ho la prossima riunione con il team?",
     {"intent": "query_schedule", "contact": "team", "query_type": "next_occurrence"}),
    ("Ho qualcosa il 3 novembre?",
     {"intent": "query_schedule", "date": "3 novembre"}),
    ("Dimmi cosa ho fissato per mercoledì pomeriggio.",
     {"intent": "query_schedule", "date": "mercoledì", "time": "pomeriggio"}),
    ("Sono occupato sabato mattina?",
     {"intent": "query_schedule", "date": "sabato", "time": "mattina", "query_type": "availability"}),
    ("Quanti appuntamenti ho questo mese con il commercialista?",
     {"intent": "query_schedule", "contact": "commercialista", "date": "questo mese", "query_type": "count"}),
    ("Cosa ho alle 9 di domani?",
     {"intent": "query_schedule", "date": "domani", "time": "09:00"}),
    ("Ci sono eventi importanti questa settimana?",
     {"intent": "query_schedule", "date": "questa settimana", "query_type": "overview"}),
]

# ─────────────────────────────────────────────────────────────────────────────
# ADD CONTACT (20)
# ─────────────────────────────────────────────────────────────────────────────
pairs += [
    ("Aggiungi Marco Bianchi con numero 333-1234567.",
     {"intent": "add_contact", "name": "Marco Bianchi", "phone": "333-1234567"}),
    ("Salva il contatto del fornitore: Tecnoservice, 02-98765432.",
     {"intent": "add_contact", "name": "Tecnoservice", "phone": "02-98765432", "role": "fornitore"}),
    ("Aggiungi Sara Conti, email sara.conti@esempio.it.",
     {"intent": "add_contact", "name": "Sara Conti", "email": "sara.conti@esempio.it"}),
    ("Nuovo contatto: Andrea Rossi, responsabile commerciale, cell. 347-9876543.",
     {"intent": "add_contact", "name": "Andrea Rossi", "phone": "347-9876543", "role": "responsabile commerciale"}),
    ("Salva il numero del medico di base: dottor Ferretti, 06-12345678.",
     {"intent": "add_contact", "name": "Dottor Ferretti", "phone": "06-12345678", "role": "medico"}),
    ("Aggiungi Giulia Marini come contatto: giulia.marini@lavoro.com, 328-4567890.",
     {"intent": "add_contact", "name": "Giulia Marini", "email": "giulia.marini@lavoro.com", "phone": "328-4567890"}),
    ("Crea un nuovo contatto per lo studio legale Rossi e Associati: 055-9988776.",
     {"intent": "add_contact", "name": "Studio Legale Rossi e Associati", "phone": "055-9988776", "role": "avvocato"}),
    ("Aggiungi il contatto: Luca Neri, project manager, luca.neri@azienda.it.",
     {"intent": "add_contact", "name": "Luca Neri", "email": "luca.neri@azienda.it", "role": "project manager"}),
    ("Salva questo numero come Officina Auto: 011-3344556.",
     {"intent": "add_contact", "name": "Officina Auto", "phone": "011-3344556"}),
    ("Nuovo fornitore: Mario Esposito, commercialista, 081-7654321, m.esposito@fiscale.it.",
     {"intent": "add_contact", "name": "Mario Esposito", "phone": "081-7654321", "email": "m.esposito@fiscale.it", "role": "commercialista"}),
    ("Aggiungi il numero di emergenza dell'edificio: 800-123456.",
     {"intent": "add_contact", "name": "Emergenza Edificio", "phone": "800-123456", "note": "numero di emergenza"}),
    ("Crea contatto per il nuovo cliente: Fabio Romano, Confezioni Romano srl.",
     {"intent": "add_contact", "name": "Fabio Romano", "note": "Confezioni Romano srl", "role": "cliente"}),
    ("Salva il recapito del tecnico informatico: Stefano, 347-1122334.",
     {"intent": "add_contact", "name": "Stefano", "phone": "347-1122334", "role": "tecnico informatico"}),
    ("Aggiungi contatto: agenzia immobiliare Casa e Più, info@casaepiu.it, 02-55667788.",
     {"intent": "add_contact", "name": "Casa e Più", "email": "info@casaepiu.it", "phone": "02-55667788", "role": "agenzia immobiliare"}),
    ("Nuovo contatto: prof. Carla Gentile, docente universitaria, c.gentile@univ.it.",
     {"intent": "add_contact", "name": "Prof. Carla Gentile", "email": "c.gentile@univ.it", "role": "docente universitaria"}),
    ("Salva il numero della palestra come FitClub: 02-44556677.",
     {"intent": "add_contact", "name": "FitClub", "phone": "02-44556677", "role": "palestra"}),
    ("Aggiungi il contatto del consulente aziendale: Ing. Davide Moro, 333-9988776, d.moro@consulenze.it.",
     {"intent": "add_contact", "name": "Ing. Davide Moro", "phone": "333-9988776", "email": "d.moro@consulenze.it", "role": "consulente aziendale"}),
    ("Nuovo contatto per la spedizione: DHL, supporto 199-199345, cliente n. 3456789.",
     {"intent": "add_contact", "name": "DHL", "phone": "199-199345", "note": "numero cliente 3456789", "role": "corriere"}),
    ("Salva il contatto del responsabile HR: Valeria Ferri, v.ferri@risorse.it.",
     {"intent": "add_contact", "name": "Valeria Ferri", "email": "v.ferri@risorse.it", "role": "responsabile HR"}),
    ("Aggiungi alla rubrica: idraulico di fiducia, Sergio Ricci, 339-8877665.",
     {"intent": "add_contact", "name": "Sergio Ricci", "phone": "339-8877665", "role": "idraulico"}),
]

# ─────────────────────────────────────────────────────────────────────────────
# SCRITTURA JSONL
# ─────────────────────────────────────────────────────────────────────────────
out = Path(__file__).parent.parent / "data" / "sft_mini.jsonl"
with open(out, "w", encoding="utf-8") as f:
    for prompt, completion in pairs:
        record = {
            "prompt": prompt,
            "completion": json.dumps(completion, ensure_ascii=False)
        }
        f.write(json.dumps(record, ensure_ascii=False) + "\n")

counts = {}
for _, c in pairs:
    intent = json.loads(json.dumps(c))["intent"]
    counts[intent] = counts.get(intent, 0) + 1

print(f"Scritto: {out}")
print(f"Totale coppie: {len(pairs)}")
for intent, n in sorted(counts.items()):
    print(f"  {intent:<22} {n:3d}")
